-- source: 010_create_bt_trf_trafico_datos.sql
CREATE TABLE APP_GOLD.BT_TRF_TRAFICO_DATOS
(
  ID_DWH_DIA                        NUMBER,
  ID_DWH_HORA                       NUMBER,
  ID_DWH_PERIODO                    NUMBER(10),
  DATE_EVENT                        NUMBER(10),
  TIME_EVENT                        VARCHAR2(6 BYTE),
  ID_STATUS_CDR                     NUMBER,
  SERVED_MSISDN                     VARCHAR2(32 BYTE),
  SERVED_IMSI                       VARCHAR2(32 BYTE),
  SERVED_IMEI                       VARCHAR2(32 BYTE),
  ID_CUENTA                         NUMBER,
  CUST_TYPE                         VARCHAR2(4 BYTE),
  ACCESS_POINT_NAME_NI              VARCHAR2(40 BYTE),
  COUNTRYCODE                       VARCHAR2(3 BYTE),
  ID_PLAN                           NUMBER,
  RECORDSEQUENCENUMBER              NUMBER,
  LOCALSEQUENCENUMBER               VARCHAR2(30 BYTE),
  CELL_INDETIFIER                   VARCHAR2(32 BYTE),
  LOCATION_AREA_CODE                VARCHAR2(32 BYTE),
  CAUSE_REC_CLOS                    NUMBER,
  DATA_VOLUME_GPRS_UPLINK_RATE      NUMBER,
  DATA_VOLUME_GPRS_UPLINK_NORATE    NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_RATE    NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_NORATE  NUMBER,
  ID_RATING_GROUP                   NUMBER,
  NODO_ID                           NUMBER,
  CHARGING_ID                       VARCHAR2(40 BYTE),
  RATTYPE                           NUMBER,
  DESC_TIPO_TECNOLOGIA              VARCHAR2(30 BYTE),
  USERLOCATIONINFORMATION           VARCHAR2(60 BYTE),
  STARTTIME                         VARCHAR2(20 BYTE),
  STOPTIME                          VARCHAR2(20 BYTE),
  RECORD_TYPE                       VARCHAR2(8 BYTE),
  DURATION_EVENT                    NUMBER,
  FILE_INPUT                        VARCHAR2(100 BYTE),
  FILE_OUTPUT                       VARCHAR2(100 BYTE),
  DATE_PROCESS                      NUMBER,
  CANTREGISTROS                     NUMBER,
  CANTNAVEGACIONRATE                NUMBER,
  CANTNAVEGACIONNORATE              NUMBER,
  NUMNAVEGACION_2G_RATE             NUMBER,
  NUMNAVEGACION_3G_RATE             NUMBER,
  NUMNAVEGACION_4G_RATE             NUMBER,
  NUMNAVEGACION_2G_NORATE           NUMBER,
  NUMNAVEGACION_3G_NORATE           NUMBER,
  NUMNAVEGACION_4G_NORATE           NUMBER,
  RED                               NUMBER,
  TIPO_ABONADO                      NUMBER,
  CGI_ORIGINAL                      VARCHAR2(60 BYTE),
  SGSN_ADDRESS                      VARCHAR2(32 BYTE),
  GGSN_ADDRESS                      VARCHAR2(32 BYTE),
  SERVED_PDP_ADDRESS                VARCHAR2(32 BYTE),
  IOT                               VARCHAR2(20 BYTE),
  DATA_VOLUME_GPRS_UPLINK_5G        NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_5G      NUMBER,
  ID_CIA                            NUMBER(1) DEFAULT 1,
  TIPO_NEGOCIO                      VARCHAR2(30 BYTE)
);

-- source: 020_create_agg_resumen_archivos_trafico.sql
CREATE TABLE APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO
(
  ID_DWH_DIA            NUMBER(10),
  ID_DWH_PERIODO        NUMBER(10),
  FILE_OUTPUT           VARCHAR2(100 BYTE),
  TIPO_TRAF             VARCHAR2(10 BYTE),
  Q_REGISTROS           NUMBER(19),
  VOLUMEN_ORIGEN        NUMBER(19),
  SEGUNDOS_ORIGEN       NUMBER(19),
  EVENTOS_ORIGEN        NUMBER(19),
  Q_REGISTROS_OK        NUMBER(19),
  VOLUMEN_OK            NUMBER(38),
  SEGUNDOS_OK           NUMBER(19),
  EVENTOS_OK            NUMBER(19),
  CANTEVENTOS_DISCARD   NUMBER(38),
  VOLUMEN_DISCARD       NUMBER(38),
  SEGUNDOS_DISCARD      NUMBER(19),
  EVENTOS_DISCARD       NUMBER(19),
  CANTEVENTOS_SUSPEND   NUMBER(19),
  VOLUMEN_SUSPEND       NUMBER(19),
  SEGUNDOS_SUSPEND      NUMBER(19),
  EVENTOS_SUSPEND       NUMBER(19),
  CANTEVENTOS_REJECT    NUMBER(19),
  VOLUMEN_REJECT        NUMBER(19),
  SEGUNDOS_REJECT       NUMBER(19),
  EVENTOS_REJECT        NUMBER(19),
  CANTEVENTOS_FILT      NUMBER(19),
  VOLUMEN_FILT          NUMBER(19),
  SEGUNDOS_FILT         NUMBER(19),
  EVENTOS_FILT          NUMBER(19),
  CANTEVENTOS_ENCOLADO  NUMBER(38),
  VOLUMEN_ENCOLADO      NUMBER(38),
  SEGUNDOS_ENCOLADO     NUMBER(19),
  EVENTOS_ENCOLADO      NUMBER(19)
);

CREATE TABLE APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO
AS
SELECT *
FROM APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO
WHERE 1 = 0;

-- source: 040_create_load_agg_resumen_archivos_trafico.sql
CREATE OR REPLACE PROCEDURE APP_GOLD.LOAD_AGG_RESUMEN_ARCHIVOS_TRAFICO (
    p_process_date   IN VARCHAR2,
    p_file_uri_list  IN VARCHAR2
) AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO';

    DBMS_CLOUD.COPY_DATA(
        table_name      => 'STG_AGG_RESUMEN_ARCHIVOS_TRAFICO',
        credential_name => NULL,
        file_uri_list   => p_file_uri_list,
        format          => JSON_OBJECT(
            'type' VALUE 'csv',
            'skipheaders' VALUE 1,
            'ignoreblanklines' VALUE TRUE,
            'trimspaces' VALUE 'lrtrim'
        )
    );

    MERGE INTO APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO tgt
    USING APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO src
       ON (
           tgt.ID_DWH_DIA = src.ID_DWH_DIA
       AND tgt.ID_DWH_PERIODO = src.ID_DWH_PERIODO
       AND tgt.FILE_OUTPUT = src.FILE_OUTPUT
       AND tgt.TIPO_TRAF = src.TIPO_TRAF
       )
    WHEN MATCHED THEN UPDATE SET
      tgt.Q_REGISTROS = src.Q_REGISTROS,
      tgt.VOLUMEN_ORIGEN = src.VOLUMEN_ORIGEN,
      tgt.SEGUNDOS_ORIGEN = src.SEGUNDOS_ORIGEN,
      tgt.EVENTOS_ORIGEN = src.EVENTOS_ORIGEN,
      tgt.Q_REGISTROS_OK = src.Q_REGISTROS_OK,
      tgt.VOLUMEN_OK = src.VOLUMEN_OK,
      tgt.SEGUNDOS_OK = src.SEGUNDOS_OK,
      tgt.EVENTOS_OK = src.EVENTOS_OK,
      tgt.CANTEVENTOS_DISCARD = src.CANTEVENTOS_DISCARD,
      tgt.VOLUMEN_DISCARD = src.VOLUMEN_DISCARD,
      tgt.SEGUNDOS_DISCARD = src.SEGUNDOS_DISCARD,
      tgt.EVENTOS_DISCARD = src.EVENTOS_DISCARD,
      tgt.CANTEVENTOS_SUSPEND = src.CANTEVENTOS_SUSPEND,
      tgt.VOLUMEN_SUSPEND = src.VOLUMEN_SUSPEND,
      tgt.SEGUNDOS_SUSPEND = src.SEGUNDOS_SUSPEND,
      tgt.EVENTOS_SUSPEND = src.EVENTOS_SUSPEND,
      tgt.CANTEVENTOS_REJECT = src.CANTEVENTOS_REJECT,
      tgt.VOLUMEN_REJECT = src.VOLUMEN_REJECT,
      tgt.SEGUNDOS_REJECT = src.SEGUNDOS_REJECT,
      tgt.EVENTOS_REJECT = src.EVENTOS_REJECT,
      tgt.CANTEVENTOS_FILT = src.CANTEVENTOS_FILT,
      tgt.VOLUMEN_FILT = src.VOLUMEN_FILT,
      tgt.SEGUNDOS_FILT = src.SEGUNDOS_FILT,
      tgt.EVENTOS_FILT = src.EVENTOS_FILT,
      tgt.CANTEVENTOS_ENCOLADO = src.CANTEVENTOS_ENCOLADO,
      tgt.VOLUMEN_ENCOLADO = src.VOLUMEN_ENCOLADO,
      tgt.SEGUNDOS_ENCOLADO = src.SEGUNDOS_ENCOLADO,
      tgt.EVENTOS_ENCOLADO = src.EVENTOS_ENCOLADO
    WHEN NOT MATCHED THEN INSERT
    (
      ID_DWH_DIA, ID_DWH_PERIODO, FILE_OUTPUT, TIPO_TRAF, Q_REGISTROS, VOLUMEN_ORIGEN,
      SEGUNDOS_ORIGEN, EVENTOS_ORIGEN, Q_REGISTROS_OK, VOLUMEN_OK, SEGUNDOS_OK, EVENTOS_OK,
      CANTEVENTOS_DISCARD, VOLUMEN_DISCARD, SEGUNDOS_DISCARD, EVENTOS_DISCARD, CANTEVENTOS_SUSPEND,
      VOLUMEN_SUSPEND, SEGUNDOS_SUSPEND, EVENTOS_SUSPEND, CANTEVENTOS_REJECT, VOLUMEN_REJECT,
      SEGUNDOS_REJECT, EVENTOS_REJECT, CANTEVENTOS_FILT, VOLUMEN_FILT, SEGUNDOS_FILT, EVENTOS_FILT,
      CANTEVENTOS_ENCOLADO, VOLUMEN_ENCOLADO, SEGUNDOS_ENCOLADO, EVENTOS_ENCOLADO
    )
    VALUES
    (
      src.ID_DWH_DIA, src.ID_DWH_PERIODO, src.FILE_OUTPUT, src.TIPO_TRAF, src.Q_REGISTROS, src.VOLUMEN_ORIGEN,
      src.SEGUNDOS_ORIGEN, src.EVENTOS_ORIGEN, src.Q_REGISTROS_OK, src.VOLUMEN_OK, src.SEGUNDOS_OK, src.EVENTOS_OK,
      src.CANTEVENTOS_DISCARD, src.VOLUMEN_DISCARD, src.SEGUNDOS_DISCARD, src.EVENTOS_DISCARD, src.CANTEVENTOS_SUSPEND,
      src.VOLUMEN_SUSPEND, src.SEGUNDOS_SUSPEND, src.EVENTOS_SUSPEND, src.CANTEVENTOS_REJECT, src.VOLUMEN_REJECT,
      src.SEGUNDOS_REJECT, src.EVENTOS_REJECT, src.CANTEVENTOS_FILT, src.VOLUMEN_FILT, src.SEGUNDOS_FILT, src.EVENTOS_FILT,
      src.CANTEVENTOS_ENCOLADO, src.VOLUMEN_ENCOLADO, src.SEGUNDOS_ENCOLADO, src.EVENTOS_ENCOLADO
    );

    COMMIT;
END;
/
