CREATE USER app_gold IDENTIFIED BY replace_me DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO app_gold;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO app_gold;
