DEFINE control_schema = MDL_CTL
DEFINE control_password = replace_me

CREATE USER &control_schema IDENTIFIED BY "&control_password" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO &control_schema;
GRANT CREATE TABLE TO &control_schema;
GRANT CREATE VIEW TO &control_schema;
GRANT CREATE SEQUENCE TO &control_schema;
GRANT CREATE PROCEDURE TO &control_schema;
GRANT CREATE SYNONYM TO &control_schema;

CREATE TABLE &control_schema.CTL_WORKFLOW (
  WORKFLOW_ID VARCHAR2(128) PRIMARY KEY,
  PROJECT_ID VARCHAR2(128),
  WORKFLOW_NAME VARCHAR2(256),
  ENTITY_NAME VARCHAR2(256),
  SOURCE_TYPE VARCHAR2(64),
  SOURCE_ASSET_REF VARCHAR2(512),
  TARGET_ASSET_REF VARCHAR2(512),
  DEFAULT_LAYER VARCHAR2(64),
  QUALITY_PROFILE VARCHAR2(256),
  METADATA_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE &control_schema.CTL_ENTITY (
  ENTITY_NAME VARCHAR2(256) PRIMARY KEY,
  PROJECT_ID VARCHAR2(128),
  SOURCE_TYPE VARCHAR2(64),
  SOURCE_SYSTEM VARCHAR2(128),
  DEFAULT_LAYER VARCHAR2(64),
  PARTITION_PATTERN VARCHAR2(512),
  TECHNICAL_COLUMNS_JSON CLOB,
  CONTRACT_REF VARCHAR2(512),
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE &control_schema.CTL_RUN (
  RUN_ID VARCHAR2(128) PRIMARY KEY,
  WORKFLOW_ID VARCHAR2(128),
  PARENT_RUN_ID VARCHAR2(128),
  PROJECT_ID VARCHAR2(128),
  ENTITY_NAME VARCHAR2(256),
  SOURCE_TYPE VARCHAR2(64),
  LAYER_NAME VARCHAR2(64),
  SLICE_KEY VARCHAR2(512),
  BUSINESS_DATE VARCHAR2(64),
  BATCH_ID VARCHAR2(128),
  WATERMARK_LOW VARCHAR2(256),
  WATERMARK_HIGH VARCHAR2(256),
  REPROCESS_REQUEST_ID VARCHAR2(128),
  SOURCE_ASSET_REF VARCHAR2(512),
  TARGET_ASSET_REF VARCHAR2(512),
  SERVICE_RUN_REF VARCHAR2(256),
  QUALITY_PROFILE VARCHAR2(256),
  STATUS VARCHAR2(64),
  METRICS_JSON CLOB,
  METADATA_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_RUN_01 ON &control_schema.CTL_RUN (WORKFLOW_ID, ENTITY_NAME, LAYER_NAME);
CREATE INDEX &control_schema.IX_CTL_RUN_02 ON &control_schema.CTL_RUN (PARENT_RUN_ID, REPROCESS_REQUEST_ID);

CREATE TABLE &control_schema.CTL_RUN_STEP (
  STEP_ID VARCHAR2(256) PRIMARY KEY,
  RUN_ID VARCHAR2(128) NOT NULL,
  WORKFLOW_ID VARCHAR2(128),
  SERVICE_NAME VARCHAR2(128),
  COMMAND_NAME VARCHAR2(128),
  LAYER_NAME VARCHAR2(64),
  SLICE_KEY VARCHAR2(512),
  STATUS VARCHAR2(64),
  SERVICE_RUN_REF VARCHAR2(256),
  ROWS_IN NUMBER,
  ROWS_OUT NUMBER,
  ROWS_REJECTED NUMBER,
  METRICS_JSON CLOB,
  METADATA_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_RUN_STEP_01 ON &control_schema.CTL_RUN_STEP (RUN_ID, SERVICE_NAME);

CREATE TABLE &control_schema.CTL_RUN_SLICE (
  SLICE_ID VARCHAR2(256) PRIMARY KEY,
  RUN_ID VARCHAR2(128) NOT NULL,
  WORKFLOW_ID VARCHAR2(128),
  ENTITY_NAME VARCHAR2(256),
  LAYER_NAME VARCHAR2(64),
  SLICE_KEY VARCHAR2(512),
  BUSINESS_DATE VARCHAR2(64),
  BATCH_ID VARCHAR2(128),
  SOURCE_ASSET_REF VARCHAR2(512),
  TARGET_ASSET_REF VARCHAR2(512),
  STATUS VARCHAR2(64),
  ROWS_IN NUMBER,
  ROWS_OUT NUMBER,
  ROWS_REJECTED NUMBER,
  CHECKSUM_REF VARCHAR2(512),
  PROFILE_REF VARCHAR2(512),
  METRICS_JSON CLOB,
  METADATA_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_RUN_SLICE_01 ON &control_schema.CTL_RUN_SLICE (RUN_ID, SLICE_KEY);

CREATE TABLE &control_schema.CTL_CHECKPOINT (
  CHECKPOINT_ID VARCHAR2(256) PRIMARY KEY,
  WORKFLOW_ID VARCHAR2(128),
  LAST_RUN_ID VARCHAR2(128),
  ENTITY_NAME VARCHAR2(256),
  LAYER_NAME VARCHAR2(64),
  SLICE_KEY VARCHAR2(512),
  CHECKPOINT_TYPE VARCHAR2(64),
  CHECKPOINT_VALUE VARCHAR2(2048),
  WATERMARK_LOW VARCHAR2(256),
  WATERMARK_HIGH VARCHAR2(256),
  STATUS VARCHAR2(64),
  PAYLOAD_JSON CLOB,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_CHECKPOINT_01 ON &control_schema.CTL_CHECKPOINT (ENTITY_NAME, LAYER_NAME, SLICE_KEY);

CREATE TABLE &control_schema.CTL_REPROCESS_REQUEST (
  REPROCESS_REQUEST_ID VARCHAR2(128) PRIMARY KEY,
  WORKFLOW_ID VARCHAR2(128),
  PARENT_RUN_ID VARCHAR2(128),
  ENTITY_NAME VARCHAR2(256),
  LAYER_NAME VARCHAR2(64),
  REQUEST_SCOPE VARCHAR2(64),
  SLICE_KEY VARCHAR2(512),
  BUSINESS_DATE VARCHAR2(64),
  BATCH_ID VARCHAR2(128),
  REQUESTED_REASON VARCHAR2(1024),
  REQUESTED_BY VARCHAR2(256),
  STATUS VARCHAR2(64),
  PAYLOAD_JSON CLOB,
  REQUESTED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_REPROCESS_REQUEST_01 ON &control_schema.CTL_REPROCESS_REQUEST (WORKFLOW_ID, ENTITY_NAME, SLICE_KEY);

CREATE TABLE &control_schema.CTL_QUALITY_RESULT (
  QUALITY_RESULT_ID VARCHAR2(256) PRIMARY KEY,
  RUN_ID VARCHAR2(128),
  WORKFLOW_ID VARCHAR2(128),
  SLICE_KEY VARCHAR2(512),
  CONTRACT_NAME VARCHAR2(256),
  GATE_NAME VARCHAR2(256),
  SEVERITY_THRESHOLD VARCHAR2(64),
  STATUS VARCHAR2(64),
  FAILED_CHECKS NUMBER,
  REPORT_REF VARCHAR2(1024),
  METRICS_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX &control_schema.IX_CTL_QUALITY_RESULT_01 ON &control_schema.CTL_QUALITY_RESULT (RUN_ID, SLICE_KEY, CONTRACT_NAME);

CREATE TABLE &control_schema.CTL_LINEAGE_OUTBOX (
  LINEAGE_EVENT_ID VARCHAR2(256) PRIMARY KEY,
  RUN_ID VARCHAR2(128),
  WORKFLOW_ID VARCHAR2(128),
  SLICE_KEY VARCHAR2(512),
  EVENT_TYPE VARCHAR2(64),
  PROVIDER_KEY VARCHAR2(256),
  NAMESPACE_NAME VARCHAR2(256),
  SOURCE_ASSET_REF VARCHAR2(512),
  TARGET_ASSET_REF VARCHAR2(512),
  STATUS VARCHAR2(64),
  PAYLOAD_JSON CLOB,
  CREATED_AT_UTC TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PUBLISHED_AT_UTC TIMESTAMP
);

CREATE INDEX &control_schema.IX_CTL_LINEAGE_OUTBOX_01 ON &control_schema.CTL_LINEAGE_OUTBOX (STATUS, RUN_ID, SLICE_KEY);
