CREATE USER app_gold IDENTIFIED BY "APP_GOLD_PASSWORD" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO app_gold;
GRANT CREATE TABLE TO app_gold;
GRANT CREATE VIEW TO app_gold;
GRANT CREATE SEQUENCE TO app_gold;
GRANT CREATE PROCEDURE TO app_gold;
GRANT CREATE SYNONYM TO app_gold;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO app_gold;
GRANT EXECUTE ON DBMS_CLOUD TO app_gold;
