CREATE TABLE APP_GOLD.BT_TRF_TRAFICO_DATOS
(
  ID_DWH_DIA                        NUMBER,
  ID_DWH_HORA                       NUMBER,
  ID_DWH_PERIODO                    NUMBER(10),
  DATE_EVENT                        NUMBER(10),
  TIME_EVENT                        VARCHAR2(6 BYTE),
  ID_STATUS_CDR                     NUMBER,
  SERVED_MSISDN                     VARCHAR2(32 BYTE),
  SERVED_IMSI                       VARCHAR2(32 BYTE),
  SERVED_IMEI                       VARCHAR2(32 BYTE),
  ID_CUENTA                         NUMBER,
  CUST_TYPE                         VARCHAR2(4 BYTE),
  ACCESS_POINT_NAME_NI              VARCHAR2(40 BYTE),
  COUNTRYCODE                       VARCHAR2(3 BYTE),
  ID_PLAN                           NUMBER,
  RECORDSEQUENCENUMBER              NUMBER,
  LOCALSEQUENCENUMBER               VARCHAR2(30 BYTE),
  CELL_INDETIFIER                   VARCHAR2(32 BYTE),
  LOCATION_AREA_CODE                VARCHAR2(32 BYTE),
  CAUSE_REC_CLOS                    NUMBER,
  DATA_VOLUME_GPRS_UPLINK_RATE      NUMBER,
  DATA_VOLUME_GPRS_UPLINK_NORATE    NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_RATE    NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_NORATE  NUMBER,
  ID_RATING_GROUP                   NUMBER,
  NODO_ID                           NUMBER,
  CHARGING_ID                       VARCHAR2(40 BYTE),
  RATTYPE                           NUMBER,
  DESC_TIPO_TECNOLOGIA              VARCHAR2(30 BYTE),
  USERLOCATIONINFORMATION           VARCHAR2(60 BYTE),
  STARTTIME                         VARCHAR2(20 BYTE),
  STOPTIME                          VARCHAR2(20 BYTE),
  RECORD_TYPE                       VARCHAR2(8 BYTE),
  DURATION_EVENT                    NUMBER,
  FILE_INPUT                        VARCHAR2(100 BYTE),
  FILE_OUTPUT                       VARCHAR2(100 BYTE),
  DATE_PROCESS                      NUMBER,
  CANTREGISTROS                     NUMBER,
  CANTNAVEGACIONRATE                NUMBER,
  CANTNAVEGACIONNORATE              NUMBER,
  NUMNAVEGACION_2G_RATE             NUMBER,
  NUMNAVEGACION_3G_RATE             NUMBER,
  NUMNAVEGACION_4G_RATE             NUMBER,
  NUMNAVEGACION_2G_NORATE           NUMBER,
  NUMNAVEGACION_3G_NORATE           NUMBER,
  NUMNAVEGACION_4G_NORATE           NUMBER,
  RED                               NUMBER,
  TIPO_ABONADO                      NUMBER,
  CGI_ORIGINAL                      VARCHAR2(60 BYTE),
  SGSN_ADDRESS                      VARCHAR2(32 BYTE),
  GGSN_ADDRESS                      VARCHAR2(32 BYTE),
  SERVED_PDP_ADDRESS                VARCHAR2(32 BYTE),
  IOT                               VARCHAR2(20 BYTE),
  DATA_VOLUME_GPRS_UPLINK_5G        NUMBER,
  DATA_VOLUME_GPRS_DOWNLINK_5G      NUMBER,
  ID_CIA                            NUMBER(1) DEFAULT 1,
  TIPO_NEGOCIO                      VARCHAR2(30 BYTE)
);

