CREATE TABLE APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO
(
  ID_DWH_DIA            NUMBER(10),
  ID_DWH_PERIODO        NUMBER(10),
  FILE_OUTPUT           VARCHAR2(100 BYTE),
  TIPO_TRAF             VARCHAR2(10 BYTE),
  Q_REGISTROS           NUMBER(19),
  VOLUMEN_ORIGEN        NUMBER(19),
  SEGUNDOS_ORIGEN       NUMBER(19),
  EVENTOS_ORIGEN        NUMBER(19),
  Q_REGISTROS_OK        NUMBER(19),
  VOLUMEN_OK            NUMBER(38),
  SEGUNDOS_OK           NUMBER(19),
  EVENTOS_OK            NUMBER(19),
  CANTEVENTOS_DISCARD   NUMBER(38),
  VOLUMEN_DISCARD       NUMBER(38),
  SEGUNDOS_DISCARD      NUMBER(19),
  EVENTOS_DISCARD       NUMBER(19),
  CANTEVENTOS_SUSPEND   NUMBER(19),
  VOLUMEN_SUSPEND       NUMBER(19),
  SEGUNDOS_SUSPEND      NUMBER(19),
  EVENTOS_SUSPEND       NUMBER(19),
  CANTEVENTOS_REJECT    NUMBER(19),
  VOLUMEN_REJECT        NUMBER(19),
  SEGUNDOS_REJECT       NUMBER(19),
  EVENTOS_REJECT        NUMBER(19),
  CANTEVENTOS_FILT      NUMBER(19),
  VOLUMEN_FILT          NUMBER(19),
  SEGUNDOS_FILT         NUMBER(19),
  EVENTOS_FILT          NUMBER(19),
  CANTEVENTOS_ENCOLADO  NUMBER(38),
  VOLUMEN_ENCOLADO      NUMBER(38),
  SEGUNDOS_ENCOLADO     NUMBER(19),
  EVENTOS_ENCOLADO      NUMBER(19)
);

CREATE TABLE APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO
AS
SELECT *
FROM APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO
WHERE 1 = 0;
