CREATE OR REPLACE PROCEDURE APP_GOLD.LOAD_AGG_RESUMEN_ARCHIVOS_TRAFICO (
    p_process_date   IN VARCHAR2,
    p_file_uri_list  IN VARCHAR2
) AS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO';

    DBMS_CLOUD.COPY_DATA(
        table_name      => 'STG_AGG_RESUMEN_ARCHIVOS_TRAFICO',
        credential_name => NULL,
        file_uri_list   => p_file_uri_list,
        format          => JSON_OBJECT(
            'type' VALUE 'csv',
            'skipheaders' VALUE 1,
            'ignoreblanklines' VALUE TRUE,
            'trimspaces' VALUE 'lrtrim'
        )
    );

    MERGE INTO APP_GOLD.AGG_RESUMEN_ARCHIVOS_TRAFICO tgt
    USING APP_GOLD.STG_AGG_RESUMEN_ARCHIVOS_TRAFICO src
       ON (
           tgt.ID_DWH_DIA = src.ID_DWH_DIA
       AND tgt.ID_DWH_PERIODO = src.ID_DWH_PERIODO
       AND tgt.FILE_OUTPUT = src.FILE_OUTPUT
       AND tgt.TIPO_TRAF = src.TIPO_TRAF
       )
    WHEN MATCHED THEN UPDATE SET
      tgt.Q_REGISTROS = src.Q_REGISTROS,
      tgt.VOLUMEN_ORIGEN = src.VOLUMEN_ORIGEN,
      tgt.SEGUNDOS_ORIGEN = src.SEGUNDOS_ORIGEN,
      tgt.EVENTOS_ORIGEN = src.EVENTOS_ORIGEN,
      tgt.Q_REGISTROS_OK = src.Q_REGISTROS_OK,
      tgt.VOLUMEN_OK = src.VOLUMEN_OK,
      tgt.SEGUNDOS_OK = src.SEGUNDOS_OK,
      tgt.EVENTOS_OK = src.EVENTOS_OK,
      tgt.CANTEVENTOS_DISCARD = src.CANTEVENTOS_DISCARD,
      tgt.VOLUMEN_DISCARD = src.VOLUMEN_DISCARD,
      tgt.SEGUNDOS_DISCARD = src.SEGUNDOS_DISCARD,
      tgt.EVENTOS_DISCARD = src.EVENTOS_DISCARD,
      tgt.CANTEVENTOS_SUSPEND = src.CANTEVENTOS_SUSPEND,
      tgt.VOLUMEN_SUSPEND = src.VOLUMEN_SUSPEND,
      tgt.SEGUNDOS_SUSPEND = src.SEGUNDOS_SUSPEND,
      tgt.EVENTOS_SUSPEND = src.EVENTOS_SUSPEND,
      tgt.CANTEVENTOS_REJECT = src.CANTEVENTOS_REJECT,
      tgt.VOLUMEN_REJECT = src.VOLUMEN_REJECT,
      tgt.SEGUNDOS_REJECT = src.SEGUNDOS_REJECT,
      tgt.EVENTOS_REJECT = src.EVENTOS_REJECT,
      tgt.CANTEVENTOS_FILT = src.CANTEVENTOS_FILT,
      tgt.VOLUMEN_FILT = src.VOLUMEN_FILT,
      tgt.SEGUNDOS_FILT = src.SEGUNDOS_FILT,
      tgt.EVENTOS_FILT = src.EVENTOS_FILT,
      tgt.CANTEVENTOS_ENCOLADO = src.CANTEVENTOS_ENCOLADO,
      tgt.VOLUMEN_ENCOLADO = src.VOLUMEN_ENCOLADO,
      tgt.SEGUNDOS_ENCOLADO = src.SEGUNDOS_ENCOLADO,
      tgt.EVENTOS_ENCOLADO = src.EVENTOS_ENCOLADO
    WHEN NOT MATCHED THEN INSERT
    (
      ID_DWH_DIA, ID_DWH_PERIODO, FILE_OUTPUT, TIPO_TRAF, Q_REGISTROS, VOLUMEN_ORIGEN,
      SEGUNDOS_ORIGEN, EVENTOS_ORIGEN, Q_REGISTROS_OK, VOLUMEN_OK, SEGUNDOS_OK, EVENTOS_OK,
      CANTEVENTOS_DISCARD, VOLUMEN_DISCARD, SEGUNDOS_DISCARD, EVENTOS_DISCARD, CANTEVENTOS_SUSPEND,
      VOLUMEN_SUSPEND, SEGUNDOS_SUSPEND, EVENTOS_SUSPEND, CANTEVENTOS_REJECT, VOLUMEN_REJECT,
      SEGUNDOS_REJECT, EVENTOS_REJECT, CANTEVENTOS_FILT, VOLUMEN_FILT, SEGUNDOS_FILT, EVENTOS_FILT,
      CANTEVENTOS_ENCOLADO, VOLUMEN_ENCOLADO, SEGUNDOS_ENCOLADO, EVENTOS_ENCOLADO
    )
    VALUES
    (
      src.ID_DWH_DIA, src.ID_DWH_PERIODO, src.FILE_OUTPUT, src.TIPO_TRAF, src.Q_REGISTROS, src.VOLUMEN_ORIGEN,
      src.SEGUNDOS_ORIGEN, src.EVENTOS_ORIGEN, src.Q_REGISTROS_OK, src.VOLUMEN_OK, src.SEGUNDOS_OK, src.EVENTOS_OK,
      src.CANTEVENTOS_DISCARD, src.VOLUMEN_DISCARD, src.SEGUNDOS_DISCARD, src.EVENTOS_DISCARD, src.CANTEVENTOS_SUSPEND,
      src.VOLUMEN_SUSPEND, src.SEGUNDOS_SUSPEND, src.EVENTOS_SUSPEND, src.CANTEVENTOS_REJECT, src.VOLUMEN_REJECT,
      src.SEGUNDOS_REJECT, src.EVENTOS_REJECT, src.CANTEVENTOS_FILT, src.VOLUMEN_FILT, src.SEGUNDOS_FILT, src.EVENTOS_FILT,
      src.CANTEVENTOS_ENCOLADO, src.VOLUMEN_ENCOLADO, src.SEGUNDOS_ENCOLADO, src.EVENTOS_ENCOLADO
    );

    COMMIT;
END;
/
